# Generated by Django 4.1 on 2022-11-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_posts_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
