# Generated by Django 4.1 on 2022-11-07 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
