# Generated by Django 4.1 on 2022-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('none', 'NONE'), ('client', 'CLIENT'), ('handler', 'HANDLER'), ('operator', 'OPERATOR')], default='none', max_length=20),
        ),
    ]
