# Generated by Django 4.1 on 2022-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteercenter", "0004_welfare_prescription_delivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="client",
            new_name="delivery_client",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="client",
            new_name="prescription_client",
        ),
        migrations.RenameField(
            model_name="welfare",
            old_name="client",
            new_name="welfare_client",
        ),
        migrations.AlterField(
            model_name="user",
            name="address_1",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_2",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="user",
            name="county",
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="user",
            name="postcode",
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
