# Generated by Django 4.1 on 2022-11-11 16:46

from django.db import migrations, models
import volunteercenter.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0006_delivery_order_number_prescription_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number, max_length=7),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number, max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number, max_length=7),
        ),
    ]
