# Generated by Django 4.1 on 2022-11-12 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0007_alter_delivery_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
