# Generated by Django 4.1 on 2022-11-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0009_alter_delivery_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welfare_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
