# Generated by Django 4.1 on 2022-11-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0015_alter_delivery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
