# Generated by Django 4.1 on 2022-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0016_alter_delivery_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
