# Generated by Django 4.1 on 2022-11-24 14:50

from django.db import migrations, models
import volunteercenter.models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0017_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='order_number',
            field=models.IntegerField(blank=True, default=volunteercenter.models.generate_order_number),
        ),
    ]
