# Generated by Django 4.1 on 2022-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteercenter', '0019_rename_token_user_token_det_user_token_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_det',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_use',
        ),
    ]
