# Generated by Django 4.1 on 2022-10-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingTitle', to='auctions.bid'),
        ),
    ]
